http:
  routers:
    router-app-server:
      entryPoints:
        - http
      service: app-server
      rule: Host(`localhost`) && PathPrefix(`/msx-server`)
      middlewares:
        - strip-app-server
    router-app-upload-server:
      entryPoints:
        - http
      service: app-upload-server
      rule: Host(`localhost`) && PathPrefix(`/msx-upload`)
      middlewares:
        - strip-app-upload-server
    router-app-mail-server:
      entryPoints:
        - http
      service: app-mail-server
      rule: Host(`localhost`) && PathPrefix(`/msx-mail`)
      middlewares:
        - strip-app-mail-server

  services:
    app-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3010
    app-upload-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3020
    app-mail-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3030

  middlewares:
    strip-app-server:
      stripPrefix:
        prefixes:
          - '/msx-server'
    strip-app-upload-server:
      stripPrefix:
        prefixes:
          - '/msx-upload'
    strip-app-mail-server:
      stripPrefix:
        prefixes:
          - '/msx-mail'
