http:
  routers:
    router-app-server-docs-api:
      entryPoints:
        - http
      service: app-server
      rule: Host(`localhost`) && PathPrefix(`/msx-server/`)
      middlewares:
        - strip-app-server-docs-api
    router-app-upload-server-docs-api:
      entryPoints:
        - http
      service: app-upload-server
      rule: Host(`localhost`) && PathPrefix(`/msx-upload/`)
      middlewares:
        - strip-app-upload-server-docs-api
    router-app-mail-server-docs-api:
      entryPoints:
        - http
      service: app-mail-server
      rule: Host(`localhost`) && PathPrefix(`/msx-mail/`)
      middlewares:
        - strip-app-mail-server-docs-api
    router-app-server:
      entryPoints:
        - http
      service: app-server
      rule: 'Host(`localhost`) &&
      (
        PathPrefix(`/product/`) ||
        PathPrefix(`/product-definition/`) ||
        PathPrefix(`/brand/`) ||
        PathPrefix(`/category/`)
      )'

  services:
    app-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3010
    app-upload-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3020
    app-mail-server:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3030

  middlewares:
    strip-app-server-docs-api:
      stripPrefix:
        prefixes:
          - '/msx-server'
    strip-app-upload-server-docs-api:
      stripPrefix:
        prefixes:
          - '/msx-upload'
    strip-app-mail-server-docs-api:
      stripPrefix:
        prefixes:
          - '/msx-mail'
