version: '3.9'

networks:
  gateway-network:
    external: true

volumes:
  postgres-data:
  redis-data:
  traefik-data:
  rabbitmq-data:

services:
  local-postgres:
    image: postgres:15.2
    restart: 'no'
    container_name: local-postgres
    ports:
      - 5432:5432
    volumes:
      - ../../cerbos/cerbos.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc12345
    networks:
      - gateway-network

  local-redis:
    image: redis:7.0.12
    restart: 'no'
    container_name: local-redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass abc12345
    volumes:
      - redis-data:/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - gateway-network

  local-rabbitmq:
    image: rabbitmq:3.12.2-management
    restart: 'no'
    container_name: local-rabbitmq
    hostname: local-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=abc12345
    networks:
      - gateway-network

  local-traefik:
    image: traefik:v2.9.8
    restart: 'no'
    container_name: local-traefik
    ports:
      - target: 3000
        published: 3000
        mode: host
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # traefik logs
      - traefik-data:/logs
      # traefik config
      - ../../traefik/traefik.yml:/etc/traefik/traefik.yml
      # traefik file provider
      - ../../traefik/dynamic.yaml:/dynamic/dynamic.yaml
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$Yem0Wlpo$$PMK2N5GIdk1dLWQgtQSPK0 #abc12345 password
      - traefik.http.routers.traefik-public-http.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.service=api@internal
      - traefik.http.routers.traefik-public-http.middlewares=admin-auth
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    networks:
      - gateway-network

  local-cerbos:
    container_name: local-cerbos
    restart: 'no'
    image: ghcr.io/cerbos/cerbos:latest
    command: ['server', '--config=/config/config.yaml']
    volumes:
      - ../../cerbos/config:/config
    ports:
      - 3592:3592
      - 3593:3593
